### ISSUE TITLE
PETSCII-VIC II Keyboard/Character Errors

### ISSUE THREAD

**Issue by bluecursor** [mkrueger/icy_term#61] opened 2023-10-02 22:58 UTC
Typing [SHIFT]0-9 Displays either the character twice or the wrong character. Also [SHIFT]- (underscore) does not work.

**Comment by mkrueger** [comment] 2023-10-05 11:57
Duplicate of https://github.com/mkrueger/icy_term/issues/55

**Closed by mkrueger** 2023-10-05 11:57 UTC
