### ISSUE TITLE
Issue with VicII+Petscii when calling a BBS 

### ISSUE THREAD

**Issue by bluecursor** [mkrueger/icy_term#57] opened 2023-09-25 21:57 UTC
Compared to other terminals, Icy terms seems to be a bit off when it comes to displaying the Petcii graphics. Does Icy needs a specific petscii font? I use [C64 TrueType v1.2.1/Style](https://style64.org/release/c64-truetype-v1.2.1-style)

IcyTerm
![Screenshot 2023-09-25 at 5 44 46 PM](https://github.com/mkrueger/icy_term/assets/31462938/f371c2f0-688f-424b-8e32-3eb3fc21904e)

MuffinTerm:
![Screenshot 2023-09-25 at 5 46 15 PM](https://github.com/mkrueger/icy_term/assets/31462938/3476a7e0-a235-4105-8480-aae6bccc31af)

CCGMSx
![Screenshot 2023-09-25 at 5 53 24 PM](https://github.com/mkrueger/icy_term/assets/31462938/2e5e037a-b8a9-4d7b-9597-ce146601009c)

**Comment by mrdudz** [comment] 2023-09-26 02:04
That looks like inverse mode is not handled at all :) (It's a good idea to just use a chrgen ROM dump and render the glyphs directly, instead of using a font for this)

I noticed problems with DEL too, and also with cursor movements

It should be noted, that a PETSCII terminal must exactly reproduce how the C64s kernal chrout output works ($ffd2) - including the weird quirks like quote-mode and logical lines. Else the output will not work correctly under all conditions.

**Comment by mkrueger** [comment] 2023-09-29 12:21
I render bitfonts atm.

**Comment by mkrueger** [comment] 2023-09-29 16:21
will be fixed in 0.6.8 - broke it during a refactoring.

Didn't test 0.6.7 enough - atm I'm busy writing an ansi drawing tool and they share the output engine so changes for the drawing tool may affect the terminal. I'll update 0.6.8 this weekend atm I think saturday.

Still have some bugs to fix.

**Comment by mkrueger** [comment] 2023-09-30 14:53
0.6.8 fixes that.

**Closed by mkrueger** 2023-09-30 14:53 UTC
