### ISSUE TITLE
Sixel graphic cannot be over-written

### ISSUE THREAD

**Issue by skipper1947** [mkrueger/icy_term#54] opened 2023-09-24 12:58 UTC
Once a sixel graphic is displayed, it cannot be selectively over-written (as opposed to clearing the entire screen). For an example, run the Chess Club program on my board (dura-bbs.net:6359) and enter the "D)isplay settings" option. It will display a list of options in the right-hand panel, one of which is a sample Sixel graphic. Once you Q)uit out of the Display Settings secreen, the right-hand panel should replaced with the Main Menu. You can see that the sample sixel graphic is still there, covering up part of the Main Menu (it gets cleared normally in SyncTERM).

**Comment by mkrueger** [comment] 2023-09-25 14:49
Never really thought about that because sixels are somewhat alien to terminal system. I'll look what syncterm does there.

ps. my ansi drawing tool will support sixels :)

**Comment by mkrueger** [comment] 2023-09-29 14:37
Should be fixed in 0.6.8.

I plan to update this weekend - I've a few regressions in C64 & ZMODEM.

**Comment by skipper1947** [comment] 2023-09-29 16:07
OK, thanks!

    On Friday, September 29, 2023 at 07:37:29 AM PDT, Mike Krüger ***@***.***> wrote:  
 
 


Should be fixed in 0.6.8.

I plan to update this weekend - I've a few regressions in C64 & ZMODEM.

**Comment by mkrueger** [comment] 2023-09-30 14:52
0.6.8 released.

**Closed by mkrueger** 2023-09-30 14:52 UTC

**Comment by skipper1947** [comment] 2023-09-30 14:59
Looks great. Thanks!

    On Saturday, September 30, 2023 at 07:53:09 AM PDT, Mike Krüger ***@***.***> wrote:  
 
 


Closed #54 as completed.
